#!/usr/bin/python3
#
# Arducam nvidia bug report generator.
# Copyright (C) 2022, Arducam.
#
import argparse
import select
import subprocess
import sys
import time
from datetime import datetime

def run_cmd(cmd):
    try:
        p = subprocess.run(cmd, text=True, check=False, shell=True,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        return p
        # print(p.stdout, file=self._file)
    except RuntimeError as e:
        print(f'Error: {e}')
# height_ = run_cmd("v4l2-ctl --list-formats-ext | grep Discrete | head -n 1 | awk -F 'x' '{print $1}' | sed 's/[^0-9]//g'").stdout
# width_ = run_cmd("`v4l2-ctl --list-formats-ext | grep Discrete | head -n 1 | awk -F 'x' '{print $2}'`").stdout
# print(height_)

class Report:
    def __init__(self, id, file):
        self._id = id
        self._cmds = []
        self._strs = []
        self._file = file

    def __run_cmd(self, cmd):
        print(f'** {cmd} **', file=self._file)
        try:
            p = subprocess.run(cmd, text=True, check=False, shell=True,
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            print(p.stdout, file=self._file)
        except RuntimeError as e:
            print(f'Error: {e}', file=self._file)

    def add_cmd(self, c):
        self._cmds.append(c)

    def add_str(self, s):
        self._strs.append(s)

    def exec(self):
        print(f'{"-"*80}\n{self._id}\n{"-"*80}', file=self._file)

        for c in self._cmds:
            self.__run_cmd(c)

        for s in self._strs:
            print(s, file=self._file)


def run_prog(cmd, t):
    cmd = cmd.split(' ')
    out = []
    try:
        start = time.time()
        p = subprocess.Popen(cmd, text=True, stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT, errors='ignore').commun
        poll = select.poll()
        poll.register(p.stdout, select.POLLIN)

        while p.poll() is None:
            if poll.poll(0):
                line = p.stdout.readline()
                print(line, end='', flush=True)
                out.append(line)

            if (t != 0) and (time.time() - start > t):
                p.kill()
                out = out + p.communicate()[0].splitlines(keepends=True)
                out.append('Error: ***** TIMEOUT *****')
                break

    except KeyboardInterrupt:
        p.kill()
        out = out + p.communicate()[0].splitlines(keepends=True)
        out.append('Error: ***** INTERRUPT *****')

    p.wait()
    return ''.join(out)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='libcamera-apps Bug Report Generator')
    parser.add_argument('-o', help='Report filename',
                        type=str, default='arducam-bug-report.txt')
    parser.add_argument('-t', help='Timeout (seconds) for the command to run. A value of 0 \
                                    disables the timeout.', type=float, default=0)
    args = parser.parse_args()

    # app = args.c.split(" ")[0]
    width = "v4l2-ctl --list-formats-ext | grep Discrete | head -n 1 | awk -F 'x' '{print $1}' | sed 's/[^0-9]//g'"
    height = "v4l2-ctl --list-formats-ext | grep Discrete | head -n 1 | awk -F 'x' '{print $2}'"


    reports = []
    with open(args.o, 'wt') as file:
        title = Report('nvidia Bug Report', file)
        title.add_str(
            f'Date: {datetime.now().strftime("%d-%m-%Y (%H:%M:%S)")}')
        title.add_str(f'Command: {" ".join(sys.argv)}\n')
        reports.append(title)

        hwinfo = Report('Hardware information', file)
        hwinfo.add_cmd('hostname')
        hwinfo.add_cmd('uname -r')
        reports.append(hwinfo)

        camera = Report('Camera detect', file)
        camera.add_cmd('ls /dev/video*')
        reports.append(camera)

        # Get the version with the same program specified in the run command
        ver = Report('Versions', file)
        ver.add_cmd('uname -a')
        ver.add_cmd('cat /etc/os-release')
        ver.add_cmd('cat /etc/nv_tegra_release')
        reports.append(ver)

        cmds = Report('cmd_test', file)
        height_ = run_cmd(height).stdout.strip()
        width_ = run_cmd(width).stdout.strip()
        cmds.add_cmd("timeout 5s v4l2-ctl --set-fmt-video=width={},height={},pixelformat=RG10 --set-ctrl bypass_mode=0 --stream-mmap".format(width_, height_))
        cmds.add_cmd("timeout 10s gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM),width={},height={},format=NV12' ! nvvidconv ! fpsdisplaysink video-sink=fakesink --verbose".format(width_, height_))
        reports.append(cmds)

        logs = Report('Logs', file)
        logs.add_cmd('dmesg | grep arducam')
        logs.add_cmd('dmesg | grep imx')
        logs.add_cmd('dmesg')
        reports.append(logs)

        for r in reports:
            r.exec()

        print(f'\nBug report generated to {args.o}')
        print('Please upload this file when you contact support@arducom.com')
